
name: Build Fabric mod with Gradle
on:
  push:
    branches: [ fabric-1.19.4 ]
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: Get the repository contents.
      uses: actions/checkout@v3
      with:
        clean: false
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: 17
    - name: Attempt to compile using Gradle
      run: |
       chmod +x gradlew
       ./gradlew build
    # we do not want -sources and -dev files, also this needs a github account to be downloaded via summary page.
    - name: Upload compiled mod jars.
      uses: actions/upload-artifact@v3
      with:
        name: WFGM-artifacts
        path: build/libs/*[0-9].jar
